apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grpcapp
  namespace: argocd

spec:
  destination:
    namespace: grpcapp
    server: "https://kubernetes.default.svc"
  project: default
  sources:
  - repoURL: "https://github.com/sudipto-003/grpc-exp.git"
    targetRevision: main
    ref: values

  - repoURL: "https://sudipto-003.github.io/helm-charts/"
    chart: grpc-server
    targetRevision: 0.1.0
    helm:
      valueFiles:
      - $values/helm-values/grpc-app.yaml

  syncPolicy:
    automated:
      selfHeal: true
